version: '3'

services:
  api:
    container_name: MyDocu-api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    container_name: MyDocu-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - /postgres-volume:/var/lib/postgresql/data
  adminer:
    container_name: MyDocu-adminer
    image: adminer
    ports:
      - "5050:8080"
    networks:
      - mainnet
    
networks:
  mainnet:
    driver: bridge

volumes:
  postgres-volume: